### ISSUE TITLE
Navigation UI Issue

### ISSUE THREAD

**Issue by kabilsharma** [BradKwon/Kwon.Mapbox.Android#2]
Awesome job you are doing there. Hats off to you.

We are trying to build an app with latest maplibre sdk with our own  hosted tiles. 

Using navigation package from droid on roids to get navigation core works with latest maps sdk.

Using your package to 42.6 to get UI.

(grasshopper routing engine for routing)

Now when we start our app we see maps 
. long press is drawing polyline but navigation view has following errors.

2021-03-24 17:33:12.908 26960-26960/com.example.ui_test E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.ui_test, PID: 26960
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ui_test/com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2757)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2818)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:652)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:812)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity.onCreate(MapboxNavigationActivity.java:30)
        at android.app.Activity.performCreate(Activity.java:6858)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2710)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2818)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1557)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/services/android/navigation/v5/navigation/SdkVersionChecker;
        at com.mapbox.services.android.navigation.ui.v5.instruction.ImageCreator.initializeData(ImageCreator.java:131)
        at com.mapbox.services.android.navigation.ui.v5.instruction.ImageCreator.initialize(ImageCreator.java:85)
        at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.onFinishInflate(InstructionView.java:148)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:892)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:886)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
2021-03-24 17:33:12.909 26960-26960/com.example.ui_test E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at android.view.View.inflate(View.java:21046)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeView(NavigationView.java:510)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.<init>(NavigationView.java:106)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.<init>(NavigationView.java:100)
        	... 25 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.services.android.navigation.v5.navigation.SdkVersionChecker" on path: DexPathList[[zip file "/data/app/com.example.ui_test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.ui_test-1/lib/arm64, /data/app/com.example.ui_test-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 39 more

Could you help us how to resolve it.

**Comment by souviksankar2013** [comment]
This is the code that we are using. We are using Navigation UI SDK 0.42.6 in this app and it causing the above error. https://github.com/souviksankar2013/kesari_map/tree/master
Can you help us to resolve it

**Comment by BradKwon** [comment]
Hi @kabilsharma @souviksankar2013 , sorry for this belated answer. My notification setting was off so I didn't know if there were issues reported here. Hopefully, you guys already resolved that issue.

**Comment by kabilsharma** [comment]
We eventually moved to higher version. There were lots of incompatibility
issues.

well thanks for putting good work. appreciated.

Helped us a lot.

**Comment by BradKwon** [comment]
Hi @kabilsharma , that sounds awesome :) Btw, you didn't get Kotlin coroutine issue while you moved to the higher version? I couldn't get v1.0.1 binding running cuz of that. Would be really helpful if you give me some tips.

**Comment by BradKwon** [comment]
Alright. As it seems the original issue was resolved by the reporter, I will close this issue. My apology for the belated feedback again.
